### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by ryoe** [UpstateRuby/openworks-status-page#20]
Would be nice to have some kind of client-side validation in the form on create/edit views.

**Comment by alecho** [comment]
DockYard's [ember-validations](https://github.com/dockyard/ember-validations) library seems to be widely used. There's also https://github.com/offirgolan/ember-cp-validations. It seems that because we're using a jsonapi.org compliant API and Ember Data it should be easy to just hit the server and handle the errors it returns.

**Comment by alecho** [comment]
Closed by PR #32
